@echo off
echo Initializing git repository...
git init
echo Creating README.md...
echo # Tokenize > README.md
echo Adding files to git...
git add README.md
echo Making first commit...
git commit -m "first commit"
echo Renaming branch to main...
git branch -M main
echo Git repository initialized successfully!
pause